### ISSUE TITLE
Breaks on building for a branch

### ISSUE THREAD

**Issue by hjpotter92** [iynere/compare-url#34]
### Orb version

1.2.0

### What happened

unknown return code 129 from `git merge-base` with base commit , from job 

---

```
++ sed -E 's/"vcs_revision" ://'
++ sed -E 's/[[:punct:]]//g'
++ sed -E 's/ //g'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    37  100    37    0     0   1176      0 --:--:-- --:--:-- --:--:--  1193
+ COMMIT_FROM_JOB_NUM=
+ [[ '' == ecf5ecd8e44e26ca1b7f9107f50210aebf0071a2 ]]
+ cd /home/circleci/repo
+ git merge-base --is-ancestor ecf5ecd8e44e26ca1b7f9107f50210aebf0071a2
usage: git merge-base [-a | --all] <commit> <commit>...
   or: git merge-base [-a | --all] --octopus <commit>...
   or: git merge-base --independent <commit>...
   or: git merge-base --is-ancestor <commit> <commit>
   or: git merge-base --fork-point <ref> [<commit>]

    -a, --all             output all common ancestors
    --octopus             find ancestors for a single n-way merge
    --independent         list revs not reachable from others
    --is-ancestor         is the first one ancestor of the other?
    --fork-point          find where <commit> forked from reflog of <ref>

+ RETURN_CODE=129
+ [[ 129 == 1 ]]
+ [[ 129 == '' ]]
+ echo 'unknown return code 129 from git merge-base with base commit , from job 11103'
unknown return code 129 from git merge-base with base commit , from job 11103
+ exit 1
```

This is my job config:

```YAML
version: 2.1

executors:
  base-python:
    docker:
      - image: circleci/python:3.7.3

orbs:
  compare-url: iynere/compare-url@1.2.0

jobs:
  checkout_code:
    working_directory: ~/repo
    executor: base-python
    steps:
      - checkout
      - compare-url/reconstruct:
          debug: true
          project-path: ~/repo
```
